version: 2.1

jobs:
  waitForStagingToBeUp:
    machine: true
    steps:
      - run: echo "Waiting until response from staging..."
  deployProd:
    machine: true
    steps:
      - run: echo "deploy production build"
  notifyTeamOfNewBuild:
    machine: true
    steps:
      - run: echo "Notifying team of new build pipeline..."
  acceptances1:
    machine: true
    steps:
      - run: echo "acceptances1"
  checkoutAndTest:
    machine: true
    steps:
      - run: echo "Checkout and test"
  acceptances2:
    machine: true
    steps:
      - run: echo "acceptance_tests_2"
  deployStaging:
    machine: true
    steps:
      - run: echo "desploy staging"
  notfyNewVersion:
    machine: true
    steps:
      - run: echo "Notify new version."
workflows:
  build:
    jobs:
      - checkoutAndTest
      - deployStaging:
          requires:
            - checkoutAndTest
      - waitForStagingToBeUp:
          requires:
            - deployStaging
      - acceptances1:
          requires:
            - waitForStagingToBeUp
      - acceptances2:
          requires:
            - waitForStagingToBeUp
      - deployProd:
          requires:
            - acceptances1
            - acceptances2
      - notifyTeamOfNewBuild
      - notfyNewVersion:
          requires:
            - deployProd
