version: 2.1

jobs:
  checkout_and_unit_test:
    machine: true
    steps:
      - run: echo "checkout_and_unit_test"
  deploy_backend:
    machine: true
    steps:
      - run: echo "deploy_backend"
  integration_tests_backend:
    machine: true
    steps:
      - run: echo "integration_tests_backend"
  deploy_staging:
    machine: true
    steps:
      - run: echo "deploy_staging"
  acceptance_tests_1:
    machine: true
    steps:
      - run: echo "acceptance_tests_1"
  acceptance_tests_2:
    machine: true
    steps:
      - run: echo "acceptance_tests_2"
  acceptance_tests_3:
    machine: true
    steps:
      - run: echo "acceptance_tests_3"
  acceptance_tests_4:
    machine: true
    steps:
      - run: echo "acceptance_tests_4"
  deploy_production:
    machine: true
    steps:
      - run: echo "deploy_production"
workflows:
  build:
    jobs:
      - checkout_and_unit_test
      - deploy_backend:
          requires:
            - checkout_and_unit_test
      - integration_tests_backend:
          requires:
            - deploy_backend
      - deploy_staging:
          requires:
            - integration_tests_backend
      - acceptance_tests_1:
      - acceptance_tests_2:
      - acceptance_tests_3:
      - acceptance_tests_4:
      - deploy_production:
          requires:
            - acceptance_tests_1
            - acceptance_tests_2
            - acceptance_tests_3
            - acceptance_tests_4
