version: 2.1

jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run test
  afterTests1:
    machine: true
    steps:
      - run: echo "tests 1 have passed!"
  afterTests2:
    machine: true
    steps:
      - run: echo "tests 2 have passed!"
  deploy:
    machine: true
    steps:
      - run: echo "deploy"
workflows:
  build:
    jobs:
      - checkoutAndTest
      - afterTests1:
          requires:
            - checkoutAndTest
      - afterTests2:
          requires:
            - checkoutAndTest
      - deploy:
          requires:
            - afterTests1
            - afterTests2
